apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nckaouutx-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:50c6e00fc2ecd4f1ec2bab904478cd2f5ab72d78@sha256:d95925abf5a5b1addf0e3999bf468cf178887bd47392bec29362d17eb831c433
          name: container-image
